name: Rebuild GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'players.txt'
      - 'settings.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Trigger GitHub Pages rebuild
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "<!-- rebuild at $(date) -->" >> index.html
          git add index.html
          git commit -m "Trigger GitHub Pages rebuild"
          git push